# Generated by Django 5.0 on 2024-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime_updated',
            field=models.DateTimeField(),
        ),
    ]
