# Generated by Django 5.0 on 2024-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
